### ISSUE TITLE
Window resizing seems clean the document 

### ISSUE THREAD

**Issue by piaoger** [StaffEngineer/velo#129]
How to reproduce:
1. Draw some random things
2. Resize window by double clicking title bar or dragging corner.
3. The things are disappeared..

**Comment by StaffEngineer** [comment]
Thanks for reporting. 

I am not exactly sure how tackle it for now, so any ideas/help are welcome.

There is a function that called on resize: https://github.com/StaffEngineer/velo/blob/main/src/ui_plugin/systems/resize_window.rs

Position of nodes updated in https://github.com/StaffEngineer/velo/blob/main/src/ui_plugin/systems/update_rectangle_position.rs by setting `left` and `bottom` values.

**Comment by StaffEngineer** [comment]
@piaoger interesting.

I think this code was added for fixing arrow positions on wasm. If you comment code and run velo in browser and resize window I think position of arrows gonna be broken? If commenting code fixes the issue maybe we have to revisit approach how arrows on wasm was fixed and find another way.

**Comment by StaffEngineer** [comment]
@piaoger this should be fixed by https://github.com/StaffEngineer/velo/pull/153, please re-open the issue if not.
