### ISSUE TITLE
Build broken due to bevy_embedded_assets

### ISSUE THREAD

**Issue by Toasterson** [StaffEngineer/velo#171]
SO I was trying to install the application by cloning the git repo and running `cargo install --path .` I also tried `cargo build --release` and `cargo r --release` all of them show the same errror behaviour.

First it asks to define `BEVY_ASSET_PATH` and once defined as `assets` the build fails with 
```
❯ cargo r --release
   Compiling bevy_embedded_assets v0.7.0 (https://github.com/StaffEngineer/bevy_embedded_assets?rev=d9dac8d#d9dac8de)
   Compiling tantivy v0.19.2
   Compiling bevy_pkv v0.7.0 (https://github.com/StaffEngineer/bevy_pkv?rev=bf79a1a#bf79a1ae)
   Compiling bevy_markdown v0.2.0 (/export/home/toast/workspace/rust/velo/crates/bevy_markdown)
   Compiling bevy_smud v0.5.0 (https://github.com/StaffEngineer/bevy_smud?rev=3a7e902#3a7e9023)
   Compiling toml v0.7.4
   Compiling linkify v0.9.0
error: couldn't read /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/assets/example_asset: No such file or directory (os error 2)
 --> /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/include_all_assets.rs:3:59
  |
3 | embedded.add_asset(std::path::Path::new("example_asset"), include_bytes!("assets/example_asset"));
  |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/assets/subdir/other_asset: No such file or directory (os error 2)
 --> /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/include_all_assets.rs:4:64
  |
4 | embedded.add_asset(std::path::Path::new("subdir/other_asset"), include_bytes!("assets/subdir/other_asset"));
  |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/assets/açèt: No such file or directory (os error 2)
 --> /export/home/toast/.cargo/target/release/build/bevy_embedded_assets-c856f64c88a722f0/out/include_all_assets.rs:5:50
  |
5 | embedded.add_asset(std::path::Path::new("açèt"), include_bytes!("assets/açèt"));
  |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

The following warnings were emitted during compilation:

warning: Asset folder found: assets

error: could not compile `bevy_embedded_assets` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

It looks to me to be the dependency that is broken but may be the setup to build aswell.
This happens with the master branch and the 0.7.0 tag

**Comment by Toasterson** [comment]
It also happens to me with 0.5.0

**Comment by Toasterson** [comment]
It looks to me the library treis to embed it's own assets https://github.com/StaffEngineer/bevy_embedded_assets/tree/main/assets which is a completely bogus behaviour imho.

**Comment by tigregalis** [comment]
Do you have an unusual `.cargo/config.toml`?

For me, I had to run it using
```
BEVY_ASSET_PATH="path\to\velo\assets" cargo run
```

**Comment by Toasterson** [comment]
I did set `BEVY_ASSET_PATH` and cleaned my cargo config from that settings. I had to set this variable to get this far.

Also the assets that it wants to include are inside bevy_embedded_assets which must not be included by the final app and are not present in the velo assets folder

**Comment by StaffEngineer** [comment]
> I did set `BEVY_ASSET_PATH` and cleaned my cargo config from that settings. I had to set this variable to get this far.
> 
> Also the assets that it wants to include are inside bevy_embedded_assets which must not be included by the final app and are not present in the velo assets folder

Try to set it as absolute path to velo's `assets` folder.

**Comment by Toasterson** [comment]
@StaffEngineer thanks! that worked. the Fullpath made it compile.

I never had the asset path issue with other beavy projects before and I did try with different configurations in cargo build config. But to no help. I still think it's a bug in bevy_embedded_assets that it tries to package it's own assets if it doesn't find any assets to package though.

**Comment by tigregalis** [comment]
What `bevy_embedded_assets` does is:

1. First, check `BEVY_ASSET_PATH` environment variable, then just assumes it's correct and uses it (you've given it `assets` which just assumes relative path to itself).

2. If it *isn't* set (most people), then it looks for the `target` folder, then looks for the `assets` folder within the shared parent of the `target` folder, and for most people that, but for us, who've done cargo config. This feels hacky to me but that's how it's implemented.

If you have the absolute path to the `assets` folder set in the `BEVY_ASSET_PATH` environment variable, it will work.
Or, if you have a normal cargo config (so build target is within the root of the project), it will also work with the hack above.

**Comment by Toasterson** [comment]
It's actually not for caching but to reduce the size of my workspace folder to manageable sizes. I had situations before where it would grow above 100GB of artifacts in target. If sccache can prevent that then I am happy to start uign that instead. What I wanted to note though is that the target dir is a cargo modifiable feature and build scripts are asked to not rely on the target directory being inside the source dir.

As I have ZFS I can also apply compression and block deduplication to the cargo target dir if it is shared. :)

I would find it very nice if velo had a `build.rs` that simply sets the `BEVY_ASSET_PATH` to a full path and bevy_embedded_assets asks the developer to setup the build rather than assuming things not considered stable whcih it cannot get from the env.

**Comment by StaffEngineer** [comment]
> I would find it very nice if velo had a build.rs that simply sets the BEVY_ASSET_PATH

It can be simply noted in the readme to set it as an absolute path. If anyone experiences any issues, feel free to create a pull request.

> bevy_embedded_assets asks the developer to setup the build rather than assuming things not considered stable which it cannot get from the env

feel free to create an issue on `bevy_embedded_assets` repo.
