### ISSUE TITLE
web app not work well in touch device

### ISSUE THREAD

**Issue by huang12zheng** [StaffEngineer/velo#180]
open url in touch device like mobile

https://staffengineer.github.io/velo?document=https://gist.githubusercontent.com/StaffEngineer/b8ba7a054a3852d6f88044f604bc08b7/raw/6a1631fb6763c784f5da7db13fc2f3cbd0242c0c/velo.json
With After long clikc(press).
It's like choosing everything, that is, not being able to do anything.

**Comment by StaffEngineer** [comment]
This is expected. The main platform for this app is native desktop as mentioned in readme. There were an issue related to mobile support: https://github.com/StaffEngineer/velo/issues/44 but I simple don't have enough resources to implement it. If you want to have touchpad/mobile support, please submit a PR.
