### ISSUE TITLE
Starting failed on Windows10

### ISSUE THREAD

**Issue by cnsky1103** [StaffEngineer/velo#188]
I first downloaded this [version](https://github.com/StaffEngineer/velo/releases/download/0.8.0/velo-0.8.0-x86_64-pc-windows-msvc.zip), the app started successfully only once. The second time I opened it, it quitted immediately.
I then downloaded other versions, but all failed. Then I tried to build it from source code. After `cargo run --release` I got
```
> cargo run --release
    Finished release [optimized] target(s) in 0.86s
     Running `target\release\velo.exe`
2023-07-11T07:53:22.725624Z  WARN fontdb: Failed to load a font face 0 from 'C:\Windows\Fonts\mstmc.ttf' cause malformed font.  
  
thread 'Compute Task Pool (7)' panicked at 'Document not found in pkv', src\utils.rs:64:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `velo::ui_plugin::load_systems::load_doc`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `target\release\velo.exe` (exit code: 101)
```

It seems that something goes wrong at src\utils.rs which tries to load some doc. I'm now looking into it.

**Comment by StaffEngineer** [comment]
Hello @cnsky1103 :)

It may be due to data scheme incompatibility between different versions. Try to remove data store folder: https://github.com/StaffEngineer/velo#troubleshooting let me know how it goes

**Comment by cnsky1103** [comment]
it works. sorry for not reading the document carefully

**Comment by StaffEngineer** [comment]
@cnsky1103 no problem at all. There is some bug with storage as well. I have a plan to refactor storage scheme massively in https://github.com/StaffEngineer/velo/issues/184 that should make app more stable.
