### ISSUE TITLE
Rename functionality doesn't work properly

### ISSUE THREAD

**Issue by Blessium** [StaffEngineer/velo#26]
#### Description
When using the rename functionality, I've noticed that it stops working properly if I keep the delete key pressed for a prolonged period of time. This behavior doesn't occur if the key is pressed singularly.

#### To Reproduce
1. Select a tab or filename that you want to rename.
2. Press the rename button.
3. Press and hold the delete key.

#### Expected behavior
The renaming process should work properly and be able to handle the deletion of characters even if the delete key is pressed continually.

#### Actual behavior
The renaming process freezes and stops working.

**Comment by StaffEngineer** [comment]
Oh, I didn't know GitHub automatically closes the issue when corresponding PR is closed. Feel free to re-open the issue, but it should work as expected now. Thank you for opening the issue.

**Comment by Blessium** [comment]
I think you should reopen this issue because now delete key isn't working at all.

**Comment by StaffEngineer** [comment]
@Blessium thanks for testing :) what about now?
