### ISSUE TITLE
⭐ Ideas to explore

### ISSUE THREAD

**Issue by StaffEngineer** [StaffEngineer/velo#42]
Just noting the ideas to explore... feel free to contribute your ideas here:
- executable code in rectangles (see org-babel, jupyter for inspiration)
- org-mode, markdown support in rectangles
- connection between documents and meta view of connected documents (see org-roam for inspiration)
- collaborative editing (use bevy_matchbox)
- code based drawing (see plantuml for inspiration)
- ChatGPT assistance

**Comment by huang12zheng** [comment]
1. Aggregation and tiling of sticky notes
2. The same set of notes can be accessed under different tabs

**Comment by StaffEngineer** [comment]
> 1. Aggregation and tiling of sticky notes
> 2. The same set of notes can be accessed under different tabs

Could you expand on your points? I don't understand the use cases. Feel free to join discord server (link in readme) if you want to chat about it.

**Comment by StaffEngineer** [comment]
I've created separate issues for ideas I'd like to explore, closing this issue for now.
