### ISSUE TITLE
Hex color widget

### ISSUE THREAD

**Issue by StaffEngineer** [StaffEngineer/velo#58]
Instead of having 5 colors for rectangles background let's have one default color (yellow one):
<img width="171" alt="image" src="https://user-images.githubusercontent.com/111751109/234015824-a1628e99-dae4-4479-a945-608c2f1b8270.png">
and text input near to it to change to any color: `[] #7d26cd`

**Comment by GnanaGanesh1999** [comment]
I would like to signup for this!

**Comment by GnanaGanesh1999** [comment]
Created a fork and a new branch in https://github.com/GnanaGanesh1999/velo

**Comment by StaffEngineer** [comment]
Seems like not much progress on this issue, I close it for now. This can be re-opened if someone wants to work on it.
