### ISSUE TITLE
Add tagging/untagging for documents

### ISSUE THREAD

**Issue by StaffEngineer** [StaffEngineer/velo#6]
Add editable field that allows adding/removing tags from document (position of red rectangle in the right bottom corner):

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/111751109/230742084-b3acca31-3221-4555-9709-4b4a43cc7f52.png">

Proposed syntax for tags is #tag_name1, #tag_name2, by pressing Enter editing of tags is ended.

**Comment by jeevaprakashdr** [comment]
@StaffEngineer I would like to look at this. Please can you assign this to me?

**Comment by StaffEngineer** [comment]
Instead of occupying some space on canvas better UX would be to have a button that opens modal for document tag editing.

**Comment by StaffEngineer** [comment]
This can be re-opened if someone wants to work on it.
Fuzzy search on native platform is enough for now.
