### ISSUE TITLE
Add search by document name

### ISSUE THREAD

**Issue by StaffEngineer** [StaffEngineer/velo#7]
By typing text in search box documents can be filtered by document name, e.g name: my_doc

![image](https://github.com/StaffEngineer/velo/assets/111751109/96fa465a-046b-44e8-94eb-0f4f120191c4)

**Comment by jeevaprakashdr** [comment]
@StaffEngineer  please can you assign this to me

**Comment by jeevaprakashdr** [comment]
@StaffEngineer  I am unassigning from this. Someone else can start to have a look at it.

**Comment by StaffEngineer** [comment]
This can be re-opened if someone wants to work on it.
